language: node_js   

node_js: '8'      

branches:           
  only: 
    - source

git:                
  quite: true        
  depth: 1           
  submodules: true   

cache: yarn          

install: 
  - yarn global add hexo-cli 
  - yarn

script:
  - hexo clean
  - hexo generate

deploy:              
  provider: pages    
  skip_cleanup: true 
  github_token: $GITHUB_TOKEN  
  keep_history: true 
  repo: aaro-n/aaro-n.github.io.git
  target-branch: master 
  fqdn: tabris.top
  local_dir: ./public
  email: qcqilin@gmail.com
  name: aaron
  project_name: tabris_blog_travis-ci
  on:                
    branch: matery
    all_branches: true
