language: node_js
node_js:
  - '10'

branches:
  only:
  - source

before_install:
- git config --global user.name "aaron"
- git config --global user.email "qcqilin@gmail.com"
- sed -i'' "s~https://github.com/aaro-n/aaro-n.github.io.git~https://${ACCESS_TOKEN}@github.com/aaro-n/aaro-n.github.io.git~" _config.yml

install:
- npm install hexo-cli -g
- npm install

script:
- npm run deploy
